name: Add "2024-2" label on PRs

on:
  pull_request:
    types:
      - opened

jobs:
  request:
    name: Add "2024-2" label
    runs-on: ubuntu-22.04

    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Add 2024-2 label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          url: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr edit "$url" --add-label "2024-2"
